### ISSUE TITLE
[Issue]: Unable to go fullscreen on Chromium 98 based browser

### ISSUE THREAD

**Issue by Omripresent** [jellyfin/jellyfin-web#3439]
### Please describe your bug

Using the fullscreen button or the F key bind doesn't put the window in full screen mode, DevTools console shows the following error:
`HTMLVideoElement.webkitEnterFullscreen()' is deprecated. Please use 'Element.requestFullscreen()' instead`

Steps to repreduce:
1.  Install a chromium 98 based browser
2. Play a video
3. Press f or the fullscreen button

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Browser
- Browser: Brave 1.35.101
- FFmpeg Version: 4.4.1-Jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: traefik+cloudflare
- Base URL: none
- Networking: Docker Swarm vxlan
- Storage: NFS
```

### Please attach any browser or client logs here

Deprecated Feature Used
'HTMLVideoElement.webkitEnterFullscreen()' is deprecated. Please use 'Element.requestFullscreen()' instead.
1 source
main.0f18378….bundle.js:2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmitrylyzo** [comment]
```
Chrome 98.0.4758.102
Jellyfin 10.8.0 (master)
```
Fullscreen works.

`screenfull` is probably older in 10.7.7

**Comment by matthewstrasiotto** [comment]
@dmitrylyzo 
> ```
> Chrome 98.0.4758.102
> Jellyfin 10.8.0 (master)
> ```
> 
> Fullscreen works.

Which commit were you using for this?

I'm having the same issue as @Omripresent , on:

* Chrome `99.0.4844.74 (Official Build) (64-bit)`
* Jellyfin `10.7.7`
* Jellyfin `10.8.0-alpha5`

I'm able to replicate the deprecation error :

```
Deprecated Feature Used
'HTMLVideoElement.webkitEnterFullscreen()' is deprecated. Please use 'Element.requestFullscreen()' instead.
1 source
main.0f18378….bundle.js:2
```

but from some interactive experimentation, changing to the recommended function yields: 

```
Promise {<rejected>: TypeError: fullscreen error
    at <anonymous>:1:26}
```

With some reading, as in:



https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#exceptions

> 
> [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)
> The TypeError exception may be delivered in any of the following situations:
> 
> - The document containing the element isn't fully active; that is, it's not the current active document.
> - The element is not contained by a document.
> - The element is not permitted to use the "fullscreen" feature, either because of Feature Policy configuration or other access control features.
> - The element and its document are the same node.

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#controlling_access

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/fullscreen

I came to the conclusion that this issue may actually have to do with a `Feature-Policy` header, which has possibly been affected by my reverse proxy, or middleware. 

When connecting to my public endpoint, `https://jellyfin.example.com`  **(behind a traefik reverse proxy)**, **fullscreen does not work.**

When I connect the *un-proxied http endpoint** `http://127.0.0.1:8096` (or wherever the server is listening on your local network, without being reverse-proxied), **fullscreen works as expected**

**Comment by matthewstrasiotto** [comment]
Reviewing my traefik middlewares, I find:

```yaml
http:
  middlewares:
    securityHeaders:
      headers:
        customFrameOptionsValue: SAMEORIGIN
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        sslRedirect: true
        stsPreload: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        featurePolicy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
          X-Robots-Tag: "none"
```

In particular, I note: 

```yaml
http:
  middlewares:
    securityHeaders:
      headers:
        featurePolicy: "camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
```

From the devtools "Network" tab, I find the following for  the `index.html` request:

![image](https://user-images.githubusercontent.com/39424834/159222226-003b1bc4-964e-4242-8368-19550afaed05.png)

If I were to hazard a guess, your reverse proxy's middleware headers are injecting `Feature-Policy: fullscreen 'none';`, which is restricting your apps from requesting fullscreen views.

The easiest fix, which should still be safe enough, is to just remove this from your reverse proxy config.
