### ISSUE TITLE
Live TV Image Not Displaying on >10.9.0

### ISSUE THREAD

**Issue by fishcharlie** [jellyfin/jellyfin-web#5499]
**Describe The Bug**

After upgrading to version 10.9.0, the Live TV image no longer shows up. Every other image shows just fine.

**Steps To Reproduce**

1. Have custom Live TV image
2. Upgrade to 10.9.0

**Expected Behavior**

Live TV custom image to show as expected

**Logs**

**Screenshots**

<img width="931" alt="Screenshot 2024-05-13 at 3 28 22 PM" src="https://github.com/jellyfin/jellyfin-web/assets/860375/f10aa63e-5fbc-455b-bb5b-d0d798afe607">

<img width="1569" alt="Screenshot 2024-05-13 at 3 29 54 PM" src="https://github.com/jellyfin/jellyfin-web/assets/860375/4ca6a045-9b7d-46aa-b0b3-99144b0ddbe3">

**System (please complete the following information):**
 - Platform: Docker
 - Browser: Safari Version 17.4.1 (19618.1.15.11.14)
 - Jellyfin Version: 10.9.0 & 10.9.1

**Additional Context**

I have tried deleting the custom image and re-uploading it. That worked for just a bit (I think until the next refresh). Then it stopped displaying again.

**Comment by fishcharlie** [comment]
Seems like this is very random. Maybe 1 in 50 page loads it works fine and shows the image as expected. It just showed up perfectly fine when I navigated to the page. Then I refreshed and the image didn't show up again.

**Comment by fernvenue** [comment]
Hi, same issue here, and I just found out that it occurs everytime I refresh the homepage or when a user logs in for the first time. I have a temporary solution for this, you can add the following lines to the custom CSS in the settings:

```css
.cardImageContainer.defaultCardBackground.defaultCardBackground3.cardContent.itemAction[aria-label="Live TV"] {
    background-image: url('https://example.com/.....');
    background-size: cover;
    background-position: center;
}

.cardImageContainer.defaultCardBackground.defaultCardBackground3.cardContent.itemAction[aria-label="Live TV"] .cardImageIcon.material-icons.live_tv[aria-hidden="true"] {
    display: none;
}
```

Remember to replace the background image url with your LiveTV image url, you can find it using the developer tools (aka F12) in your browser when Jellyfin correctly loads your LiveTV image. And if your Jellyfin consistently fails to load the LiveTV image preventing you from finding the url, try going to the settings and then returning to the homepage.

Hope this issue can be resolved soon :)
