### ISSUE TITLE
Subtitles have a different shadow than my settings

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-web#5602]
**Describe The Bug**
When I play something, the subtitles have this shadow that look like a drop shadow, even though I changed it to 'uniform' in the settings.

**Steps To Reproduce**

1. Go to personal settings
2. Click on subtitles
3. Scroll down to drop shadow
4. Set to 'Uniform' 
5. Save
6. Play a video
7. See error

**Expected Behavior**
I expected the subtitles to look like the 'uniform' subtitles

**Screenshots**
This is the subtitle I expect:
![image](https://github.com/jellyfin/jellyfin-web/assets/47184046/aaa2afed-4be7-411b-bfd6-4032f02d7873)
And this is the subtitle I get:
![image](https://github.com/jellyfin/jellyfin-web/assets/47184046/0e5d5297-aaf8-4511-b0aa-33acd31dbbc6)

**System (please complete the following information):**
 - Platform: Windows 10
 - Browser: Firefox
 - Jellyfin Version: 10.9.2

**Logs**
I don't know if these errors are relevant, but they show up in the browser console.
```
HLS Error: Type: otherError Details: internalException Fatal: false main.jellyfin.bundle.js:2:73451
```
```
ReferenceError: t is not defined 38932f0f-23f6-4806-8cad-44df1f497289:1:100
```
```
HLS Error: Type: mediaError Details: bufferFullError Fatal: false 3 main.jellyfin.bundle.js:2:73451
```
```
HLS Error: Type: mediaError Details: bufferFullError Fatal: false
```

**Additional Context**
The subtitle type in the screenshot is subrip. 
Additionally, this error does not occur when using the Jellyfin Media Player desktop app (which is supposed to be a wrapper of the website right?)

**Comment by thornbill** [comment]
Duplicate of #5592

**Comment by JVT038** [comment]
Yeah, I'm using the [ultrachromic](https://github.com/CTalvio/Ultrachromic) styles.
This is the custom CSS:
```css
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/progress/floating.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/titlepage/title_simple-logo.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/type/dark.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/cornerindicator/indicator_floating.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/fields/fields_border.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/login/login_frame.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/episodelist/episodes_compactlist.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/rounding.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/base.css');@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/accentlist.css');@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/fixes.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/smallercast.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/header/header_transparent.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/effects/hoverglow.css');
@import url('https://ctalvio.github.io/Monochromic/backdrop-hack_style.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/fixes.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/smallercast.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/header/header_transparent.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/effects/hoverglow.css');
@import url('https://ctalvio.github.io/Monochromic/backdrop-hack_style.css');
:root {--accent: 98.00787045,121.00999580324999,204.99450000000002;}
.backdropImage {filter: blur(30px);}
.backdropImage {filter: saturate(120%);}
.backdropImage {filter: contrast(120%);}
.backdropImage {filter: brightness(40%);}
:root {--rounding: 12px;}
```
