### ISSUE TITLE
All text is italicized on Firefox on Linux

### ISSUE THREAD

**Issue by melvyn2** [jellyfin/jellyfin-web#6460]
**Describe The Bug**
All text on the Web UI is italicized, even when it shouldn't be.

**Steps To Reproduce**

1. Create a clean Firefox profile (from about:profiles)
2. Visit https://demo.jellyfin.org/stable/web/#/login.html
3. Observe that all text is italicized

**Expected Behavior**
The UI text is not italicized.

**Logs**

**Screenshots**
![Image](https://github.com/user-attachments/assets/5d3be956-a3ec-409f-bab0-687438fd86c9)

**System (please complete the following information):**
 - Platform: NixOS Unstable
 - Browser: Firefox 134.0.1
 - Jellyfin Version: 10.10.3

**Additional Context**
Also seen on Fedora Workstation 41 on Firefox of the same version, but not on PopOS with Firefox of the same version: https://forum.jellyfin.org/t-all-text-on-webui-is-in-italics-on-1-browser

Removing the `font-family` rule of the `html` selector shows the text in an un-italicized serif font instead. This rule:
```css
html {
  font-family: Noto Sans,Noto Sans HK,Noto Sans JP,Noto Sans KR,Noto Sans SC,Noto Sans TC,sans-serif;
}
```
However, applying the same rule to other websites does not italicize their text.

Removing the following font directive also removes the italicization while keeping the usual sans-serif font:
```css
@font-face {
  font-display:swap;
  font-family:Noto Sans;
  font-style:normal;
  font-weight:400;
  src:local("Noto Sans"),
  local("Noto Sans Regular"),
  url(c417ee867416d52e5187.woff2) format("woff2");
  unicode-range:u+00??,
  u+0131,
  u+0152-0153,
  u+02bb-02bc,
  u+02c6,
  u+02da,
  u+02dc,
  u+2000-206f,
  u+2074,
  u+20ac,
  u+2122,
  u+2191,
  u+2193,
  u+2212,
  u+2215,
  u+feff,
  u+fffd
}
```
as does removing the two `local` sources (forcing it to use the server-provided font).
