### ISSUE TITLE
White borders around the category card

### ISSUE THREAD

**Issue by EvgeniyDoctor** [jellyfin/jellyfin-web#6750]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-web/issues?q=is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

After clicking on a category, a white border appears around it.
The screenshot shows the border around the "Series Live" category.
![Image](https://github.com/user-attachments/assets/810a861e-47cc-46dc-b908-fa58dd2eb2b6)

### Reproduction Steps

1. go to main page
2. click on any category
3. you already can see the white border. Or you can press 'back' in your browser and enjoy these borders more

### Expected/Actual behaviour

No borders.

### Server version

10.10.6

### Web version

10.10.6

### Build version

10.10.6

### Platform

Linux

### Browser

Vivaldi, Brave

### Additional information

There was no such thing in the old versions (10.8.*). This bug appeared later and has been around for at least **1 year** (!).

**Comment by jagadam97** [comment]
can confirm.. 

Not that noticeable tho at least for me. 

https://github.com/user-attachments/assets/1343fc87-b0bc-4fdf-b26b-83ea48c427e5

**Comment by jagadam97** [comment]
only fix i was able to find was changing the display property of .cardImageContainer to None. Not sure if this may cause other UI issues.

But in my testing this was worrking fine.
@EvgeniyDoctor if the white borders are bothering you, you can test out my fix by add the below to custom css in your server

```scss
 .cardImageContainer {
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
    border-radius: 0.2em;
    display: none;
    align-items: center;
    justify-content: center;
    position: relative;
    background-clip: content-box !important;
    color: inherit;
    text-decoration: none;
}
```
